"""
AUTOGENERATED by git post-commit hook. Note that these are always from the PREVIOUS commit, and so may be out of date by one log entry
"""
git_branch    = "working"
git_shorthash = "9aad1ff"
git_longhash  = "9aad1ff31d2532a541daa3b2e800f9b4bad30afe"
git_last_tag  = "2.5.0"
